version: "3.9"

services:
  nginx:
    image: nginx:1.21.0-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    build: ./config/docker/php
    restart: always
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Xdsoft"
    depends_on:
      - database
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data: